const types = {
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  GETROOM_SUCCESS: 'GETROOM_SUCCESS',
  GETROOM_ERROR: 'GETROOM_ERROR',
  INSERT_ROOM_SUCCESS: 'INSERT_ROOM_SUCCESS',
  INSERT_ROOM_ERROR: 'INSERT_ROOM_ERROR',
  UPDATE_ROOM_SUCCESS: 'UPDATE_ROOM_SUCCESS',
  UPDATE_ROOM_ERROR: 'UPDATE_ROOM_ERROR',
  DELETE_ROOM_SUCCESS: 'DELETE_ROOM_SUCCESS',
  DELETE_ROOM_ERROR: 'DELETE_ROOM_ERROR'
};
export default types;
