const types = {
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  GETROOM_SUCCESS: 'GETROOM_SUCCESS',
  GETROOM_ERROR: 'GETROOM_ERROR',
  INSERT_ROOM_SUCCESS: 'INSERT_ROOM_SUCCESS',
  INSERT_ROOM_ERROR: 'INSERT_ROOM_ERROR',
  UPDATE_ROOM_SUCCESS: 'UPDATE_ROOM_SUCCESS',
  UPDATE_ROOM_ERROR: 'UPDATE_ROOM_ERROR',
  DELETE_ROOM_SUCCESS: 'DELETE_ROOM_SUCCESS',
  DELETE_ROOM_ERROR: 'DELETE_ROOM_ERROR',
  GET_EQUIPMENT_SUCCESS: 'GET_EQUIPMENT_SUCCESS',
  GET_EQUIPMENT_ERROR: 'GET_EQUIPMENT_ERROR',
  GET_EQUIPMENT_BY_ROOM_SUCCESS: 'GET_EQUIPMENT_BY_ROOM_SUCCESS',
  GET_EQUIPMENT_BY_ROOM_ERROR: 'GET_EQUIPMENT_BY_ROOM_ERROR',
  INSERT_EQUIPMENT_SUCCESS: 'INSERT_EQUIPMENT_SUCCESS',
  INSERT_EQUIPMENT_ERROR: 'INSERT_EQUIPMENT_ERROR',
  UPDATE_EQUIPMENT_SUCCESS: 'UPDATE_EQUIPMENT_SUCCESS',
  UPDATE_EQUIPMENT_ERROR: 'UPDATE_EQUIPMENT_ERROR',
  DELETE_EQUIPMENT_SUCCESS: 'DELETE_EQUIPMENT_SUCCESS',
  DELETE_EQUIPMENT_ERROR: 'DELETE_EQUIPMENT_ERROR'
};
export default types;
